spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
#        server-addr: 42.193.112.54:8848
        server-addr: 42.193.112.54  #nginx
#        server-addr: 127.0.0.1:8848

        #nacos 作为配置中心的一些配置项设置
#        namespace: dev #自定义的命名空间  默认为public
#        group: DEV_GROUP # 自定义的组名  默认为DEFAULT_GROUP
#        file-extension: yaml # 配置内容的数据格式
#        username: nacos # Nacos的登录用户名
#        password: nacos # Nacos的登录密码

server:
  port: 8001

management:
  endpoint:
    web:
      exposure:
        include: '*'