spring:
  application:
    name: team
  cloud:
    nacos:
      discovery:
        server-addr: 42.193.112.54
  datasource:
    url: jdbc:mysql://42.193.112.54:3306/nba?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: jiawei@994102
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8004

management:
  endpoint:
    web:
      exposure:
        include: '*'

mybatis:
  mapper-locations: classpath:mybatis/*.xml #指定映射文件路径
  type-aliases-package: com.chenjw.bean

mybatis-plus:
  type-aliases-package: com.chenjw.bean
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true