spring:
  application:
    name: consumer-openfeign
  cloud:
    nacos:
      discovery:
        server-addr: 42.193.112.54:8848
#        server-addr: 127.0.0.1:8848

        #nacos 作为配置中心的一些配置项设置
#        namespace: dev #自定义的命名空间  默认为public
#        group: DEV_GROUP # 自定义的组名  默认为DEFAULT_GROUP
#        file-extension: yaml # 配置内容的数据格式
#        username: nacos # Nacos的登录用户名
#        password: nacos # Nacos的登录密码

server:
  port: 9002

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeoput: 2000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 2000

# 开启sentinel
feign:
  sentinel:
    enabled: true


# 消费者将要去访问的微服务名称（注册成功的Nacos的微服务提供者）
#service-url:
#  #nacos-user-service: http://provider
#  nacos-user-service: http://sentinel-provider

management:
  endpoint:
    web:
      exposure:
        include: '*'